/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}",],
  theme: {
    extend: {
      colors: {
        customPurple: '#6840C5',
        customeGray: '#979DA6',
        customLightGray:'#D0D5DD',
        designText:'#6941C6',
        designBG:'#F9F5FF',
        designBorder:"#E9D7FC",
        productText:'#175CD3',
        productBG:'#EFF8FF',
        productBorder:"#BRDDFF",
        MarketingText:'#6367D9',
        MarketingBG:'#EEF4FF',
        MarketingBorder:"#C6D7FE",
        otherText:"#969DAF",
        otherBG:"F9FAFB",
        otherBorder:"#E4E7EC",
        VDheader:"#2A5B7E",
        VDbg:"#FFFCFC",
        VDpersonalInfo:"#EFF5FA",
        VDseePub:"#F15A22",
        VDbodyKeyText:"#101828",
        VDbodyValueText:"#64748b",
        VDheadingText:"#3E4C5F",
        editBG:"#F8FAFC",
        editbuttonText:"#050F3A",
        editBorder:"#CBD5E1",
        filterHeader:"#0F172A",
        filterBG:"#FFFCFC",
        filterHeading:"#3A4453",
        filterSubHeading:"#475467",
        editDisabledBtnBG:"#F1F5F9",
        editDisabledBtnText:"#CBD5E1",
        paginationBG:"#F9FAFB",
        paginationSelectedText:"#1D2939",
        paginationText:"#475467",
        oddRowBg:"#F9FAFB",
        borderPeopleDirectory:"#E2E8F0",
        deleteEdit:"#475467",
        peopleDirectoryText:"#465366",
        deteTextColor:"#242424",

      },
    },
  },
  plugins: [],
}

